---
# tasks file for ansible-role-win-dotnet48
- name: ansible-role-win-dotnet48 - Check installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
    name: Release
  register: dotnet48_release

- debug:
    var: dotnet48_release.exists

- debug:
    var: dotnet48_release.value

- name: ansible-role-win-dotnet48 - Download 
  win_get_url:
    url: '{{ dotnet48_download_url }}'
    dest: 'C:\Windows\Temp\{{ dotnet48_install_file }}'
    force: no
  when: dotnet48_release.value|int < 528049
  
- name: ansible-role-win-dotnet48 - Install
  win_package:
    path: 'C:\Windows\Temp\{{ dotnet48_install_file }}'
    arguments: /q /norestart
    product_id: '{F39E5132-620C-4978-AE0C-F925D685E5E6}'
    state: present 
  register: dotnet48_install
  when: dotnet48_release.value|int < 528049

- name: ansible-role-win-dotnet48 - Reboot when required
  win_reboot:
  register: has_rebooted
  when:
    - dotnet48_release.value|int < 528049
    - dotnet48_install is defined
    - dotnet48_install.reboot_required

- name: ansible-role-win-dotnet48 - Optimize-PowershellAssemblies
  win_shell: |
    $old_path = $env:path
    try {
      $env:path = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
      [AppDomain]::CurrentDomain.GetAssemblies() | % {
        if (! $_.location) {continue}
        $Name = Split-Path $_.location -leaf
        if ($Name.startswith("Microsoft.PowerShell.")) {
          Write-Progress -Activity "Native Image Installation" -Status "$name"
          ngen install $_.location | % {"`t$_"}
        }
      }
    } finally {
      $env:path = $old_path
    }
  when: 
    - has_rebooted.rebooted |default(false)
    - dotnet48_optimize_assemblies |bool

